unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on

bind -n C-S-l next-window
bind -n C-S-j previous-window
bind -n C-S-n new-window
bind -n C-S-q kill-pane
bind -n C-S-d detach-client

bind l split-window -h
bind k split-window -v
bind Left select-pane -L
bind Right select-pane -R
bind Up select-pane -U
bind Down select-pane -D

bind r source-file ~/.tmux.conf \; display "Config reloaded!"
bind -n C-S-a resize-pane -Z
bind -n C-S-w choose-session

set -g base-index 1
set -g pane-base-index 1
set -g allow-passthrough on

set -g window-status-separator ""
run-shell "~/.tmux/theme.sh"
