[preset 0]
# Basic Stats
fps
fps_metrics=avg,0.01,0.001
frametime

# CPU Info
cpu_stats
cpu_temp
cpu_mhz
cpu_power

# GPU Info
gpu_list=0
gpu_name
gpu_stats
gpu_temp
gpu_core_clock
gpu_voltage
gpu_power

# RAM / VRAM
ram
vram
swap

# Display Info
gamemode
resolution
vsync
winesync

# Style & Appearance
no_display = 0
offset_x=5
offset_y=5
round_corners=8
font_size=20
table_columns=3
background_alpha=0.35
hud_no_margin
show_fps_limit
fps_limit_method=late

[preset 1]
# Basic Stats
fps
fps_metrics=avg,0.01,0.001
frametime

# CPU Info
cpu_stats
cpu_temp
cpu_mhz
cpu_power

# GPU Info
gpu_list=0
gpu_name
gpu_stats
gpu_temp
gpu_core_clock
gpu_voltage
gpu_power

# RAM / VRAM
ram
vram
swap

# Display Info
gamemode
resolution
vsync
winesync

# Style & Appearance
no_display = 0
offset_x=5
offset_y=5
round_corners=8
font_size=20
table_columns=3
background_alpha=0.35
hud_no_margin
show_fps_limit
fps_limit_method=late
fps_limit_method=early
