version = 9

[[questions]]
question = "Questions with explanations"
choices = ["option C", "option B", "option A", "option D"]
answer = "option A"
explanations = ["explanation for C", "explanation for B", "explanation for A", "explanation for D"]

[[questions]]
question = "Let's have some fun in Minecraft."
choices = ["True", "False"]
answer = "True"
explanations = ["Of course we have to!", ""]
