version = 8

[[questions]]
question = "Arknight Endfield is Amazing!"
choices = ["True", "False"]
answer = "True"

[[questions]]
question = "Goo goo gaa gaa"
choices = ["True", "False"]
answer = "True"
