version = 9

[[questions]]
question = "Minecraft minecraft"
choices = ["False", "True"]
answer = "True"

[[questions]]
question = "Let's have some fun in Minecraft."
choices = ["True", "False"]
answer = "True"
