general {
    gaps_in = 8,3,8,3
    gaps_out = 9,5,9,5
    border_size = 2
}

decoration {
    rounding = 0
    shadow {
        enabled = false
    }
}

animations {
    enabled = no
}

unbind = SUPER, space
unbind = SUPER, escape
bind = SUPER, space, exec, qs -c tui ipc call config open_popup control_panel
bind = SUPER, escape, exec, qs -c tui ipc call launcher toggle
